package com.example.projetosd.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import com.example.projetosd.repository.ProductRepository;

@Controller
public class mainController {

    @Autowired // This means to get the bean called depRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository prodRepository;

    @GetMapping(path="/teste")
    public String getAllDeps (Model model) {
        model.addAttribute("ListDeps" , prodRepository.findAll());
        return "index";
    }

}
