package com.example.projetosd.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import com.example.projetosd.repository.ProductRepository;
import com.example.projetosd.repository.BrandRepository;
import com.example.projetosd.repository.TypeRepository;

@Controller
public class MainController {

    @Autowired // This means to get the bean called depRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository prodRepository;

    @Autowired
    private BrandRepository brandRepository;

    @Autowired
    private TypeRepository typeRepository;

    //vou tirar o resto depois quando o carro já tiver na base de dados
    @GetMapping("/")
    public String getHome(Model model) {
        model.addAttribute("ListBrands", brandRepository.findAll());
        model.addAttribute("ListTypes", typeRepository.findAll());
        model.addAttribute("marca", "Porsche 911");
        model.addAttribute("ano", "1964");
        model.addAttribute("kms", "250.000");
        model.addAttribute("caixa", "Manual");
        model.addAttribute("cor", "Amarelo");
        model.addAttribute("valor", "€230.000");
        model.addAttribute("Products", prodRepository.findAll());
        return "index";
    }

    @GetMapping(path="/teste")
    public String getAll(Model model) {
        model.addAttribute("ListDeps", prodRepository.findAll());
        model.addAttribute("ListBrands", brandRepository.findAll());
        model.addAttribute("ListTypes", typeRepository.findAll());

        return "index";
    }

}
